version: '2'

services:

  vtiger:
    build: ${version}
    environment:
      - VT_DEBUG=true
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 20080:80
      - 20443:443
    volumes:
      - ./:/app
      - ./vtiger:/var/lib/vtiger
    links:
      - mysql
      - adminer

  adminer:
    image: javanile/adminer
    environment:
      - MYSQL_DATABASE=vtiger
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 20081:8080
    links:
      - mysql

  mysql:
    image: mysql:5.5
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - mysql:/var/lib/mysql:rw
      - ./:/vtiger:rw

  debian:
    image: debian
    working_dir: /app
    command: bash -c "echo 'prevent default'; exit 0"
    volumes:
      - ./:/app:rw

volumes:
  mysql:
